name: Code Coverage
on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - '*-prod'

jobs:
  PRQualityChecks:
    runs-on: hs-releng-action-runner-ci
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'   
      
      - name: Run Unit Tests
        run: mvn clean test
